---
title: "01-garmin-process-analyze"
author: "maryhargis"
date: '2024-04-27'
output: html_document
---

#this is a working document! please check back for updates.

```{r}
library(dplyr)
library(tidyverse)
library(janitor)
library(lubridate)
library(ggplot2)
library(psych)
library(psychTools)
library(stats)
library(viridis)
options(sci_pen = 100)
```

#read in dataset
```{r}
garmin_raw_no_location <- read.csv("garmin_raw.csv") %>% clean_names

garmin_running <- garmin_raw_no_location %>% filter(str_detect(activity_type, "Running"))

```

#question 1 - are my runs better on the treadmill or outside on the road?

##processing
```{r}
#what makes a "good run" can vary depending on you talk to! Some runners are all about pace (minutes per mile), others are all about cadence (foot turnover). Overall, it's a pretty undefined ask. Below, I specify two ways to conceptualize a "good" run and analyze accordingly.

#1a: operationalizing a "good" run as a faster pace -- minutes per mile
good_run_fast <- garmin_running %>% 
  select(activity_type, distance, time, avg_pace, best_pace,  max_temp, aerobic_te, avg_run_cadence) %>% 
  mutate(across(c(distance, max_temp), as.numeric)) %>% filter(activity_type != "Trail Running")
#converting time data from character to time
good_run_fast <- good_run_fast %>% 
  mutate(total_time = hms(time),
         total_hours = hour(total_time),
         total_minutes = minute(total_time),
         total_seconds = second(total_time),
         total_time_in_minutes =(total_seconds / 60) + total_minutes) %>%
  mutate(avg_pace = ms(avg_pace),
         avg_pace_minutes = minute(avg_pace),
         avg_pace_seconds = second(avg_pace)) %>%
  mutate(avg_pace_in_minutes = (avg_pace_seconds/60)+avg_pace_minutes) %>%
  mutate(aerobic_te = as.numeric(aerobic_te))

#remove outliers on pace
mean_pace = mean(good_run_fast$avg_pace_in_minutes)
sd_pace = sd(good_run_fast$avg_pace_in_minutes)
good_run_fast <- good_run_fast %>% filter(avg_pace_in_minutes < (mean_pace + (3*sd_pace))) %>% filter(avg_pace_in_minutes > (mean_pace - (3*sd_pace)))



#1b: operationalizing a "good" run using cadence (faster running needs higher foot turnover)
good_run_cadence <- garmin_running  %>% select(activity_type, distance, avg_pace, avg_run_cadence, max_temp, aerobic_te) %>% 
  mutate(across(c(distance, max_temp), as.numeric)) %>% filter(activity_type != "Trail Running")
#converting time data from character to time
good_run_cadence <- good_run_cadence %>% 
  mutate(avg_pace = ms(avg_pace),
         avg_pace_minutes = minute(avg_pace),
         avg_pace_seconds = second(avg_pace)) %>%
  mutate(avg_pace_in_seconds = (avg_pace_seconds/60)+avg_pace_minutes) %>%
  mutate(avg_run_cadence = as.numeric(avg_run_cadence))%>%
  mutate(aerobic_te = as.numeric(aerobic_te))

#remove outliers on cadence
mean_cadence = mean(good_run_cadence$avg_run_cadence)
sd_cadence = sd(good_run_cadence$avg_run_cadence)
good_run_cadence <- good_run_cadence %>% filter(avg_run_cadence < (mean_cadence + (3*sd_cadence))) %>% filter(avg_run_cadence > (mean_cadence - (3*sd_cadence)))


```

##analysis
###descriptives
```{r}
#descriptives
##1a
describeBy(good_run_fast$avg_pace_in_minutes, good_run_fast$activity_type) #226 regular runs,  103 treadmill runs 
##1b
describeBy(good_run_cadence$avg_run_cadence, good_run_cadence$activity_type) #226 regular runs,  100 treadmill runs 
```


###initial visualization
```{r}
#1a: good run = fast run
fast_plot <- good_run_fast %>% 
  ggplot(aes (x = max_temp, y = avg_pace_in_minutes, group = activity_type, fill = activity_type))+
  geom_area() +
    scale_fill_viridis(discrete = TRUE) +
    theme(legend.position="none") +
    ggtitle("Visualizing fastest runs") +
    theme(legend.position="none",
      panel.spacing = unit(0, "lines"),
      strip.text.x = element_text(size = 8),
      plot.title = element_text(size=13)
    ) + 
    facet_wrap(~activity_type, scale="free_y")

fast_plot

#1b: good run = fast cadence
cadence_plot <- good_run_cadence %>% 
  ggplot(aes (x = max_temp, y = avg_run_cadence, group = activity_type, fill = activity_type))+
  geom_area() +
    scale_fill_viridis(discrete = TRUE) +
    theme(legend.position="none") +
    ggtitle("Visualizing fastest runs") +
    theme(legend.position="none",
      panel.spacing = unit(0, "lines"),
      strip.text.x = element_text(size = 8),
      plot.title = element_text(size=13)
    ) + 
    facet_wrap(~activity_type, scale="free_y")

cadence_plot

#these plots show us that pace and cadence are pretty variable, especially among "regular runs" (outdoor runs)/ that's the most common run type.  
max(good_run_fast$max_temp) #hottest temp during a run was 98.6 -- I don't recommend running in weather that hot, but I do live in Las Vegas!
```

###regression models
```{r}

#bare-bones models
fast_model_simple <- lm(avg_pace_in_minutes ~activity_type, data = good_run_fast)
summary(fast_model_simple) #non-sig effect of activity type on pace


cadence_model_simple <- lm(avg_run_cadence ~ activity_type, data = good_run_cadence)
summary(cadence_model_simple)#non-sig effect of activity type on cadence


#other variables that affect pace include temperature, distance traveled, aerobic exertion. variable of interest here is activity type.

fast_model <- lm(avg_pace_in_minutes ~ max_temp + distance + aerobic_te +  activity_type, data = good_run_fast)
summary(fast_model)
#results: 
#-farther distance: slower pace; 
#-more exertion: faster pace; 
#-no effect of temp. 
#-Outdoor runs are the reference group; treadmill runs are faster pace!

cadence_model <- lm(avg_run_cadence ~ max_temp + distance + aerobic_te +  activity_type, data = good_run_cadence)
summary(cadence_model)
#results: 
#-farther distance: slower cadence (tired legs = slow cadence!); 
#-more exertion: higher cadence; 
#-no effect of temp. 
#-Outdoor runs are the reference group; treadmill runs are slower cadence!
```
##figures
```{r}
#pace by activity type
cbp1 <- c( "#56B4E9", "#D55E00")

fast_plot_2 <- good_run_fast %>% 
  ggplot(aes (x = avg_pace_in_minutes, y = activity_type, color = activity_type))+
  stat_sum(aes(size = factor(..n..)), geom = "point") +
  scale_x_continuous(expand = expansion(mult = c(0, 0.1))) +
  scale_y_discrete(limits = rev) +
    labs(x = "Number of runs",
       y = "Pace (minutes per mile)",
       title = "Run pace (minutes/mile) by activity type",
       caption = "Data source: Garmin Forerunner 645") +
  theme(legend.position = "off") + scale_colour_manual(values=cbp1)
fast_plot_2

ggsave("pace_plot.png", fast_plot_2)

#pace by activity type
cbp2 <- c( "#56B4E9", "#D55E00")

cadence_plot_2 <- good_run_cadence %>% 
  ggplot(aes (x = avg_run_cadence, y = activity_type, color = activity_type))+
  stat_sum(aes(size = factor(..n..)), geom = "point") +
  scale_x_continuous(expand = expansion(mult = c(0, 0.1))) +
  scale_y_discrete(limits = rev) +
    labs(x = "Number of runs",
       y = "Cadence (steps per minute)",
       title = "Run cadence (steps/minute) by activity type",
       caption = "Data source: Garmin Forerunner 645") +
  theme(legend.position = "off") + scale_colour_manual(values=cbp2)
cadence_plot_2

ggsave("cadence_plot.png", cadence_plot_2)

```




#question 2: on days when I manage to keep my heart rate low, how do I perform compared to higher HR days?
```{r}
#...to be continued!
```

